# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.23
mod_id = onewholibs
maven_group = com.onewhohears.onewholibs
archives_name = onewholibs
enabled_platforms = fabric,forge

mod_license=MIT
mod_authors=1whohears, kawaiicakes
mod_description=A library mod for 1whohears mods.

homepage=https://github.com/1whohears
sources=https://github.com/1whohears/1wholibs
issue_tracker=https://github.com/1whohears/1wholibs/issues

# Minecraft properties
minecraft_version = 1.19.2
minecraft_version_range=[1.19.2]

# Dependencies
architectury_version = 6.6.92

fabric_loader_version = 0.16.14
fabric_api_version = 0.77.0+1.19.2

forge_version = 1.19.2-43.5.0
forge_version_range=[43,)
forge_loader_version_range=[43,)

sml_version = 1.4.0
javaglobj_version = 0.4.0

ftb_library_version=1902.4.1-build.236
ftb_teams_version=1902.2.14-build.123

openpartiesandclaims_version=0.23.7
forgeconfigapiport_version=4.2.11

fabric_openpartiesandclaims_id=6055471
forge_openpartiesandclaims_id=6055470