import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id "com.gradleup.shadow"
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/onewholibs.accesswidener")
}

dependencies {
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"

    modCompileOnly("dev.ftb.mods:ftb-library:${rootProject.ftb_library_version}") { transitive = false }
    modCompileOnly("dev.ftb.mods:ftb-teams:${rootProject.ftb_teams_version}") { transitive = false }

    implementation "de.javagl:obj:${rootProject.javaglobj_version}"
}

tasks.register("commonShadowJar", ShadowJar) {
    archiveClassifier.set("shadowed")

    configurations = [project.configurations.shadowImpl]
}

configurations {
    shadowedElements {
        canBeConsumed = true
        canBeResolved = false
    }
    shadowImpl {
        canBeResolved = true
        canBeConsumed = false
        extendsFrom implementation
    }
}

artifacts {
    shadowedElements tasks.named("commonShadowJar")
}
